import type { Cafe } from "@/types/cafe";

export const mockCafes: Cafe[] = [
  {
    placeId: "mock-kopikalyan-cikajang",
    name: "Kopikalyan Cikajang",
    location: { latitude: -6.23811, longitude: 106.80821 },
    rating: 4.6,
    userRatingCount: 1260,
    priceLevel: "MEDIUM",
    isOpenNow: true,
    primaryType: "cafe",
    photoName: null,
    googleMapsUri: "https://maps.google.com/?q=Kopikalyan+Cikajang",
  },
  {
    placeId: "mock-giyanti-coffee",
    name: "Giyanti Coffee Roastery",
    location: { latitude: -6.19398, longitude: 106.83296 },
    rating: 4.7,
    userRatingCount: 2510,
    priceLevel: "PREMIUM",
    isOpenNow: true,
    primaryType: "coffee_shop",
    photoName: null,
    googleMapsUri: "https://maps.google.com/?q=Giyanti+Coffee+Roastery",
  },
  {
    placeId: "mock-tanamera-thamrin",
    name: "Tanamera Coffee Thamrin",
    location: { latitude: -6.19673, longitude: 106.82391 },
    rating: 4.5,
    userRatingCount: 1740,
    priceLevel: "MEDIUM",
    isOpenNow: false,
    primaryType: "coffee_shop",
    photoName: null,
    googleMapsUri: "https://maps.google.com/?q=Tanamera+Coffee+Thamrin",
  },
  {
    placeId: "mock-djournal-senopati",
    name: "Djournal Coffee Senopati",
    location: { latitude: -6.22728, longitude: 106.80759 },
    rating: 4.3,
    userRatingCount: 860,
    priceLevel: "MEDIUM",
    isOpenNow: true,
    primaryType: "cafe",
    photoName: null,
    googleMapsUri: "https://maps.google.com/?q=Djournal+Coffee+Senopati",
  },
  {
    placeId: "mock-kopi-kenangan-scbd",
    name: "Kopi Kenangan SCBD",
    location: { latitude: -6.22494, longitude: 106.80933 },
    rating: 4.2,
    userRatingCount: 420,
    priceLevel: "BUDGET",
    isOpenNow: true,
    primaryType: "coffee_shop",
    photoName: null,
    googleMapsUri: "https://maps.google.com/?q=Kopi+Kenangan+SCBD",
  }
];
